import { Card, Grid } from "@nextui-org/react";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid.Container gap={2} justify="center">
          <Grid css={{ width: "320px" }}>
            <Card
              variant="flat"
              css={{ background: "$blue700", borderRadius: 5 }}
            >
              <Card.Body></Card.Body>
            </Card>
          </Grid>
          <Grid xs>
            <div>1 of 3</div>
          </Grid>
        </Grid.Container>
      </main>
    </>
  );
};

export default Home;
